#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-commons-exec
Version  : 1.3
Release  : 3
URL      : https://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
Source0  : https://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
Source1  : https://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar
Source2  : https://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.1/commons-exec-1.1.pom
Source3  : https://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.2/commons-exec-1.2.jar
Source4  : https://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.2/commons-exec-1.2.pom
Source5  : https://repo1.maven.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-commons-exec-data = %{version}-%{release}
Requires: mvn-commons-exec-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-commons-exec package.
Group: Data

%description data
data components for the mvn-commons-exec package.


%package license
Summary: license components for the mvn-commons-exec package.
Group: Default

%description license
license components for the mvn-commons-exec package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-commons-exec
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-commons-exec/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.3
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.1/commons-exec-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.2/commons-exec-1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.2/commons-exec-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.3
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar
/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.1/commons-exec-1.1.pom
/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.2/commons-exec-1.2.jar
/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.2/commons-exec-1.2.pom
/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
/usr/share/java/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-commons-exec/LICENSE.txt
